version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "babysitter-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w7fazjv91dr3"
s3_prefix = "babysitter-api"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = false
resolve_s3 = true
